# Base configuration
project: "demand_forecasting"
experiment_name: "base_experiment"

# Data configuration
# data_path, checkpoint_path, and saved_model_path are provided at runtime via command-line arguments.
target_column: "Demand(MW)"
forecasting_type: "univariate"  # or "multivariate"
features: []  # Will be populated in mode-specific configs
sequence_length: 24  # 24 hours
forecast_horizon: 1   # Predict next hour
test_size: 0.2
val_size: 0.1
random_state: 42

# --- NEW: Feature Engineering Control Panel ---
feature_engineering:
  use_time_features: true              # (true/false) Create hour, day, month features?
  use_cyclical_encoding: true          # (true/false) Convert time features to sin/cos?
  use_lag_features: true               # (true/false) Create demand_lag_24hr, etc.?
  use_rolling_window_features: true    # (true/false) Create rolling mean/std?

# Model configuration
model_type: "TCN"  # Options: LSTM, Transformer, TCN
input_size: 1      # Will be auto-set based on features
hidden_size: 64
num_layers: 2
dropout: 0.2

# Training configuration
batch_size: 64
learning_rate: 0.001
num_epochs: 50
patience: 10   # For early stopping

# Checkpointing
checkpoint_freq: 5

# W&B configuration
use_wandb: True
wandb_project: "demand_forecasting"
wandb_entity: null # This will default to your W&B username
scheduler_config:
  use_scheduler: True   # Set to True to enable the scheduler
  patience: 3           # Reduce LR if val_loss doesn't improve for 3 epochs
  factor: 0.5           # When reducing, new_lr = old_lr * 0.5
