# Configuration for the Classical Sandwich LSTM Benchmark Model
project: "demand_forecasting"
experiment_name: "Classical_Sandwich_LSTM_Benchmark"

# --- Data Configuration (Identical to L-QLSTM config) ---
target_column: "Demand(MW)"
forecasting_type: "multivariate"
features: ["Heat_Index_C", "is_weekend"]
sequence_length: 24
forecast_horizon: 1
test_size: 0.2
val_size: 0.2
random_state: 42

# Feature Engineering
feature_engineering:
  use_time_features: true
  use_cyclical_encoding: true
  use_lag_features: false
  use_rolling_window_features: false

# --- Model Configuration ---
model_type: "Classical_Sandwich_LSTM"

# Model Hyperparameters
hidden_size: 32
# For a fair benchmark, this should match n_qubits in the L-QLSTM config
classical_enhancer_size: 8

# Common Parameters
input_size: 1 # Auto-set by preprocessing
dropout: 0.1

# --- Training Configuration (Identical to L-QLSTM config) ---
batch_size: 8 # Keep batch size small to match the quantum run
learning_rate: 0.005
num_epochs: 50
patience: 10
checkpoint_freq: 5

# Scheduler Configuration
scheduler_config:
  use_scheduler: True
  mode: 'min'
  factor: 0.5
  patience: 3

# --- W&B Configuration ---
use_wandb: True
# Log to the same project for direct comparison!
wandb_project: "demand_forecasting_SOTA_Quantum"
wandb_entity: null
