# Configuration for the CNN-LSTM Model
project: "demand_forecasting"
experiment_name: "CNN_LSTM_univariate_experiment"

# --- Data Configuration ---
target_column: "Demand(MW)"
forecasting_type: "univariate"
features: []
sequence_length: 24
forecast_horizon: 1
test_size: 0.2
val_size: 0.2
random_state: 42

# --- Model Configuration ---
model_type: "CNN_LSTM"  # The key registered in the model factory

# CNN-specific parameters
cnn_out_channels: 64    # Number of filters in the convolutional layer
cnn_kernel_size: 3      # Size of the convolutional kernel (e.g., 3 time steps)

# LSTM-specific parameters (can reuse standard names)
lstm_hidden_size: 128   # Hidden units in the LSTM layer
lstm_num_layers: 2      # Number of LSTM layers

# Common parameters
input_size: 1           # Auto-set by preprocessing
dropout: 0.2

# --- Training Configuration ---
batch_size: 64
learning_rate: 0.001
num_epochs: 50
patience: 10
checkpoint_freq: 5

# --- W&B Configuration ---
use_wandb: True
wandb_project: "demand_forecasting_hourly"
wandb_entity: null
