# configs/qultsf_config.yaml

project: "demand_forecasting"
experiment_name: "QuLTSF_paper_replication"
target_column: "Demand(MW)"
forecasting_type: "univariate"
features: []
sequence_length: 168
forecast_horizon: 24
test_size: 0.2
val_size: 0.2

# --- Model Configuration ---
model_type: "qultsf"  # Set model_type to match the factory key
n_qubits: 10          # As specified in the paper (N=10) [cite: 127]
n_quantum_layers: 3   # As specified in the paper (K=3) [cite: 127]
qml_device: "lightning.qubit"


# Feature Engineering
feature_engineering:
  use_time_features: false
  use_cyclical_encoding: false
  use_lag_features: false
  use_rolling_window_features: false


# --- Training Configuration ---
batch_size: 16        # As specified in the paper [cite: 130]
learning_rate: 0.0001 # As specified in the paper [cite: 130]
num_epochs: 50
patience: 15
checkpoint_freq: 5

# Scheduler Configuration
scheduler_config:
  use_scheduler: True
  mode: 'min'
  factor: 0.5
  patience: 5

# --- W&B Configuration ---
use_wandb: True
wandb_project: "QuLTSF_replication"
wandb_entity: null