# This is a standalone version for simplicity, inheriting the structure of base_config.
# Univariate specific settings are defined.

project: "demand_forecasting"
experiment_name: "univariate_TCN_experiment"

# Data configuration
target_column: "Demand(MW)"
forecasting_type: "univariate"
features: []
sequence_length: 168
forecast_horizon: 24
test_size: 0.2
val_size: 0.2
random_state: 42

# Model configuration
model_type: "TCN"
input_size: 1
hidden_size: 64
num_layers: 2
dropout: 0.2

# Training configuration
batch_size: 32
learning_rate: 0.001
num_epochs: 50
patience: 10

# Checkpointing
checkpoint_freq: 5

# W&B configuration
use_wandb: True
wandb_project: "demand_forecasting"
wandb_entity: null
